// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    
		int N = Integer.parseInt(args[0]);
		int countGreater = 0, countLower = 0;
		double result, ratio = -1;
		
		for (int i = 0; i < N; i++)	{
			result = Math.random();
			if (result > 0.5)	countGreater++;
			else    countLower++;

			if (countGreater != 0 && countLower != 0)	{
				
				if (countGreater < countLower) {
					ratio = (double) countGreater / countLower;
				}
				else {
					ratio = (double) countLower / countGreater;
				}
			}
		}
		
		System.out.println("> 0.5: " + countGreater + " times");
		System.out.println("<= 0.5: " + countLower + " times");

		if (ratio != -1) {
			System.out.println("Ratio: " + ratio);
		}

	}
}
